# -*- coding: utf-8 -*-
"""Angielski narrator – te same klucze co NARRACJA, tylko po angielsku.

Zasada: w angielskiej wersji kwestie zapowiadające etap NIE mówią numeru
poziomu ("Level seven"), bo w trybie uproszczonym etapy są przetasowane
i numer i tak by nie pasował. Zamiast tego mówią, co się będzie działo."""

NARRACJA_EN = {
    # --- start, menu, poziomy starej numeracji ---
    'start':   "Franek's morning! Press the up arrow to start.",
    'poziom1': 'Get dressed, one thing at a time.',
    'poziom2': 'Go downstairs and make yourself some breakfast.',
    'poziom3': 'Time to brush your teeth!',
    'poziom4': 'Coat and shoes on, we are going out!',
    'poziom5': 'Off to the car, Dad is already waiting.',
    'poziom6': 'We are driving to preschool!',
    'poziom7': 'A race with Dad to the preschool gate!',
    'poziom8': 'The cloakroom! Take your things off and hug Dad.',
    'poziom9': 'A race to the window. Be quick and wave to Dad!',
    'zad_majtki':      'Find your pants!',
    'zad_spodnie':     'Now your trousers!',
    'zad_skarpetki':   'Now your socks!',
    'zad_koszulka':    'Now your t-shirt!',
    'zad_miska':       'Find a bowl!',
    'zad_platki':      'Now the cereal!',
    'zad_mleko':       'Now the milk!',
    'zad_lyzka':       'Find a spoon!',
    'zad_sniadanie':   'Eat your breakfast!',
    'zad_pasta':       'Find the toothpaste!',
    'zad_szczoteczka': 'Find your toothbrush!',
    'zad_zeby':        'Go to the sink!',
    'zad_czapka':      'Find your hat!',
    'zad_kurtka':      'Now your coat!',
    'zad_buty':        'Now your shoes!',
    'zad_drzwi':       'Go to the door!',
    'zad_samochod':    'Get in the car!',
    'brawo1': 'Well done!',
    'brawo2': 'Super!',
    'brawo3': 'You are doing great!',
    'brawo4': 'Awesome!',
    'zle':    'Not yet. Take the thing that is glowing!',
    'mycie':        'Brush your teeth! Press left and right.',
    'mycie_koniec': 'Your teeth are sparkling clean! Well done!',
    'jazda':        'Off we go! Up and down arrows change lanes.',
    'jedzenie':     'Yum yum! Tasty cereal with milk.',
    'ups':          'Oops! Careful!',
    'wybor':        'Who do you want to be? Press left for Franek, right for Pola.',
    'zad_przytulas': 'And now give Dad a goodbye hug!',
    'przytulas':     'What a great hug! Bye Dad, see you later!',
    'wyscig':        'Press the left and right arrows to run faster!',
    'wyscig_start':  'Three, two, one, go!',
    'wygrana':       'You won! Well done!',
    'pomachaj':      'Wave to Dad through the window! Bye bye!',
    'zad_zdejmij_buty':   'Take off your shoes!',
    'zad_zdejmij_kurtke': 'Hang up your coat!',
    'zad_zdejmij_czapke': 'Take off your hat!',
    'zad_okno':   'Run to the window!',
    'zad_furtka': 'Run to the gate!',
    'koniec':     'Well done Franek! You made it! You are at preschool!',
    # --- Pola, stara numeracja ---
    'p_start':   "Pola's morning! Press the up arrow to start.",
    'p_koniec':  'Well done Pola! You made it! You are at preschool!',
    'p_poziom1': 'Get up Pola! Time to climb out of bed.',
    'p_poziom2': 'To the bathroom! Brush your teeth.',
    'p_poziom3': 'Feed the fish!',
    'p_poziom4': 'Get dressed!',
    'p_poziom5': 'Time for breakfast.',
    'p_poziom6': 'We are going to preschool!',
    'zad_kapcie':   'Find your slippers!',
    'zad_mis':      'Take your teddy!',
    'zad_grzebien': 'Comb your hair!',
    'zad_karma':    'Find the fish food!',
    'zad_rybka':    'Feed the fish!',
    'zad_legginsy': 'Now your leggings!',
    'zad_bluza':    'Now your jumper!',
    'mama_czeka':   'Mum is already waiting at the door!',
    'szybciej':     'Faster Dad! Zoom!',
    'szybciej2':    'Dad, drive faster! Zoom!',
    # --- mycie zębów ---
    'mycie2':          'Scrub left and right! Up and down arrows change teeth.',
    'zeby_gora_przod': 'Top teeth at the front!',
    'zeby_dol_przod':  'Bottom teeth at the front!',
    'zeby_gora_tyl':   'Now the top ones from the inside!',
    'zeby_dol_tyl':    'Now the bottom ones from the inside!',
    'zeby_strefa_ok':  'These teeth are shiny already!',
    'zeby_minuta':     'One more minute of brushing!',
    'zeby_pol':        'Half a minute left!',
    'zeby_20':         'Twenty more seconds!',
    'licz5': 'Five!',
    'licz4': 'Four!',
    'licz3': 'Three!',
    'licz2': 'Two!',
    'licz1': 'One!',
    # --- światło, wstawanie, siku ---
    'poziom_swiatlo':   'It is dark! Turn on the light in your room.',
    'poziom_wstawanie': 'Get up Franek! Climb out of bed.',
    'poziom_siku':      'Off to the toilet for a wee!',
    'swiatlo_jak':      'Reach out to the wall. Left and right arrows move your hand, '
                        'and the up arrow presses.',
    'swiatlo_ok':       'Light! Well done Franek!',
    'swiatlo_zle':      'That is not it. Look for the switch on the wall!',
    'wstawanie_jak':    'Press left and right, one after the other, to get out of bed!',
    'wstawanie_ok':     'You are up! Well done! Now off to the toilet.',
    'wstawanie_spij':   'Do not fall asleep! Press faster!',
    'siku_jak':         'Aim into the toilet. Left arrow is nearer, right is further. '
                        'Do not splash the seat!',
    'siku_deska':       'Oops! Aim at the water in the middle!',
    'siku_ok':          'All inside and the seat is clean! Well done! Time to flush.',
    'siku_koniec':      'Flushing. Now wash your hands!',
    'siku_wybor':       'How do we wee? Left arrow means standing up, and then you have to aim. '
                        'Right arrow means sitting down, and nothing gets splashed. '
                        'The up arrow starts.',
    'siku_siedzac':     'You sit down on the seat and sit still. Everything goes straight in, '
                        'so nothing gets splashed.',
    'siku_splucz':      'All done! Press the up arrow and flush.',
    'siku_brudno':      'Oh dear, the seat and the floor are splashed. We have to clean up.',
    'siku_sprzatanie':  'If you splash the seat or the floor, you have to clean it. '
                        'Press left and right, one after the other, to wipe.',
    'siku_wytrzyj':     'Take the paper and wipe the seat. Back and forth!',
    'siku_podloga':     'Now the mop! Clean the puddle on the floor.',
    'siku_posprzatane': 'Everything is spotless! Well done! Next time aim for the middle.',
    # --- etapy Franka (bez numerów) ---
    'f_poziom4':  'Get dressed, one thing at a time.',
    'f_poziom5':  'Go downstairs and make yourself some breakfast.',
    'f_poziom6':  'Time to brush your teeth!',
    'f_poziom7':  'Hat, coat and shoes. We are going out!',
    'f_poziom8':  'Off to the car, Dad is already waiting.',
    'f_poziom9':  'We are driving to preschool!',
    'f_poziom10': 'A race with Dad to the preschool gate!',
    'f_poziom11': 'The cloakroom! Take your things off and hug Dad.',
    'f_poziom12': 'A race to the window. Be quick and wave to Dad!',
    'f_poziom13': 'Morning circle! Say hello to all the children.',
    'f_poziom14': 'A whole day at preschool!',
    'f_poziom15': 'Dad is here! Run away if you do not want a wash!',
    'f_poziom16': 'We are driving home and listening to the Cat Gang.',
    'f_poziom17': 'Filling up the car. Do not spill the petrol!',
    'f_poziom18': 'Walking home. Say hello to Igor!',
    'f_poziom19': 'We are home, Mum is waiting at the door.',
    'f_poziom20': 'Playtime at home! The train set, the bricks and the puzzle book.',
    'f_poziom21': 'Climb the wall and go through the fence to Igor!',
    'f_poziom22': "Playing at Igor's, behind the fence!",
    'f_poziom23': 'Dinner! Fish and chips today.',
    'f_poziom24': 'Bath time! Wash every part of you, one by one.',
    'f_poziom25': 'Teeth and pyjamas now.',
    'f_poziom26': 'Dad will read you a bedtime book.',
    'f_poziom27': 'Franek is asleep and dreaming about cats throwing snowballs.',
    'f_koniec2':  'Well done Franek! A whole day behind you. Washed, changed and home!',
    'f_koniec3':  'Well done Franek! A whole day behind you. Playing, dinner, a bath, '
                  'a book and a dream about cats.',
}

NARRACJA_EN.update({
    # --- Pola: dwanaście etapów, warianty z mamą i tatą ---
    'p2_poziom1':  'It is dark! Turn on the light in your room.',
    'p2_poziom2':  'Get up Pola! Climb out of bed.',
    'p2_poziom3':  'Find your slippers and take your teddy.',
    'p2_poziom4':  'To the bathroom! Brush your teeth and comb your hair.',
    'p2_poziom5':  'Feed the fish!',
    'p2_poziom6':  'Get dressed, one thing at a time.',
    'p2_poziom7':  'Time for breakfast.',
    'p2_poziom8':  'Hat, coat and shoes. Mum is already waiting!',
    'p2_poziom9':  'Cycling to preschool! Pedal with the arrows!',
    'p2_poziom10': 'A race with Mum to the preschool gate!',
    'p2_poziom11': 'The cloakroom! Take your things off and hug Mum.',
    'p2_poziom12': 'The last stage! A race to the window. Be quick and wave to Mum!',
    'p_swiatlo_ok':    'Light! Well done Pola!',
    'p_wstawanie_ok':  'You are up! Well done! Where are your slippers?',
    'p_wygrana':       'You won! Well done!',
    'p_pomachaj':      'Wave to Mum through the window! Bye bye!',
    'p_przytulas':     'What a great hug! Bye Mum, see you later!',
    'p_zad_przytulas': 'And now give Mum a goodbye hug!',
    'p_szybciej':      'Faster Mum! We will be late!',
    'p_szybciej2':     'Mum, go faster! Zoom!',
    'p_rower_jak':       'Pola is riding her bike and Mum is running behind her! Press the left '
                         'and right arrows one after the other to pedal.',
    'p_nie_tak_szybko':  'Pola, not so fast! Wait for Mum!',
    'p_nie_tak_szybko2': 'Pola, not so fast! Mum cannot keep up!',
    'p_wybor_opiekuna': 'Who are you going to preschool with today? Left arrow is Mum, '
                        'right arrow is Dad. The up arrow starts.',
    'pt_zad_przytulas': 'And now give Dad a goodbye hug!',
    'pt_przytulas':     'What a great hug! Bye Dad, see you later!',
    'pt_pomachaj':      'Wave to Dad through the window! Bye bye!',
    'pt_szybciej':      'Faster Dad! We will be late!',
    'pt_szybciej2':     'Dad, go faster! Zoom!',
    'pt_rower_jak':       'Pola is riding her bike and Dad is running behind her! Press the left '
                          'and right arrows one after the other to pedal.',
    'pt_nie_tak_szybko':  'Pola, not so fast! Wait for Dad!',
    'pt_nie_tak_szybko2': 'Pola, not so fast! Dad cannot keep up!',
    'pt2_poziom8':  'Hat, coat and shoes. Dad is already waiting!',
    'pt2_poziom10': 'A race with Dad to the preschool gate!',
    'pt2_poziom11': 'The cloakroom! Take your things off and hug Dad.',
    'pt2_poziom12': 'The last stage! A race to the window. Be quick and wave to Dad!',
    # --- Franek z mamą Magdą: taksówka i autobus ---
    'f_wybor_opiekuna': 'Who are you going to preschool with today? Left arrow is Mum Magda '
                        'and a taxi, right arrow is Dad and the car. The up arrow starts.',
    'fm_poziom8':  'Off to the taxi, Mum is already waiting.',
    'fm_poziom9':  'We are riding to preschool in a taxi!',
    'fm_poziom10': 'A race with Mum to the preschool gate!',
    'fm_poziom11': 'The cloakroom! Take your things off and hug Mum.',
    'fm_poziom12': 'A race to the window. Be quick and wave to Mum!',
    'fm_poziom15': 'Mum is here! Run away if you do not want a wash!',
    'fm_poziom16': 'We are riding the bus home.',
    'fm_poziom17': 'Stamping the ticket on the bus. Do not crumple it!',
    'fm_poziom19': 'We are home, Dad is waiting at the door.',
    'fm_zad_przytulas':  'And now give Mum a goodbye hug!',
    'fm_przytulas':      'What a great hug! Bye Mum, see you later!',
    'fm_pomachaj':       'Wave to Mum through the window! Bye bye!',
    'fm_szybciej':       'Faster Mum! Zoom!',
    'fm_szybciej2':      'Mum, drive faster! Zoom!',
    'fm_lapanie_jak':    'Mum asks: shall we go and wash up? Run away! Press the arrows one '
                         'after the other.',
    'fm_lapanie_uciekl': 'You got away from Mum! No washing today!',
    'fm_dom_czysty':     'Great to see you back!',
    'fm_jazda_dom':      'Riding the bus home. Franek is humming the Cat Gang song!',
    'fm_zad_samochod':   'Get in the taxi!',
    'bilet_jak': 'Push the ticket into the machine. Hold the up arrow and let go in the green '
                 'zone so you do not crumple it!',
    'bilet_ok':  'Ticket stamped, perfectly straight! Well done.',
    'bilet_zle': 'Oh no, the ticket is crumpling! Let go!',
    # --- przedszkole i droga do domu ---
    'kolko_jak':  'Walk around the circle with the arrows, and say hello with the up arrow.',
    'kolko_ok':   'You said hello to every child! Well done!',
    'dzien_klocki': 'We are building a huge tower out of bricks!',
    'dzien_farby':  'Painting with paints. Look how messy you are!',
    'dzien_obiad':  'Lunch time! Soup and a drink.',
    'dzien_lezak':  'Nap time. Quiet now, shhh!',
    'dzien_plac':   'The playground! Sand and a slide!',
    'dzien_koniec': 'The preschool day is over. Dad is coming to get you!',
    'lapanie_jak':     'Dad asks: shall we go and wash up? Run away! Press the arrows one after '
                       'the other.',
    'lapanie_uciekl':  'You got away from Dad! No washing today!',
    'lapanie_zlapany': 'Got you! Off we go to wash your hands and face.',
    'mycie_rak':       'Washing hands and face. Scrub, scrub!',
    'jazda_dom':   'Driving home. The Cat Gang is on the radio!',
    'tank_jak':     'Hold the up arrow and fill up. Let go in the green zone, do not spill!',
    'tank_ok':      'All filled up! Not a single drop spilled. Well done!',
    'tank_rozlane': 'Oh no, the petrol is spilling! Let go!',
    'zad_igor':    'Say hello to Igor!',
    'czesc_igor':  'Hello Igor! We are going home now.',
    'dom_czysty':  'Great to have you back, boys!',
    'dom_brudny':  'What a mucky pup! Off we go to wash and change!',
    'dom_lapie':   'Got you! To the bathroom!',
    'dom_koniec':  'Washed and changed into pyjamas. Well done Franek!',
    # --- wieczór w domu ---
    'zad_tory':      'Set up the train tracks!',
    'zad_lego':      'Now the lego bricks!',
    'zad_rebusy':    'Now the puzzle book!',
    'zad_plot':      'Climb the wall and go through the fence to Igor!',
    'zad_ryba':      'Find the battered fish!',
    'zad_frytki':    'Now the chips!',
    'zad_kolacja':   'Eat your dinner!',
    'kolacja_mniam': 'Yum yum! Tasty fish and chips.',
    'zad_pizama':    'Put on your pyjamas!',
    'igor_pilka':    'We are playing football with Igor!',
    'igor_autka':    'Racing toy cars on the grass!',
    'igor_chowany':  'Playing hide and seek. Where is Igor?',
    'igor_koniec':   'Bye bye Igor! Mum is calling us for dinner.',
    'kapiel_jak':     'Bath time! Scrub with the sponge, left and right. We will wash every '
                      'part, one by one.',
    'kapiel_szyja':   'First your neck!',
    'kapiel_glowa':   'Now your head!',
    'kapiel_rece':    'Now your arms!',
    'kapiel_nogi':    'Now your legs!',
    'kapiel_pupa':    'Now your bottom!',
    'kapiel_stopy':   'And your feet too!',
    'kapiel_czysta':  'This part is squeaky clean!',
    'kapiel_recznik': 'All washed! Now dry yourself with the towel.',
    'kapiel_koniec':  'Clean and dry! Well done Franek.',
    'ksiazka_wybor':     'Which book is Dad reading today? Left and right arrows choose, '
                         'and the up arrow starts.',
    'ksiazka_muminki':   'The Moomins! Moominvalley is asleep under the snow.',
    'ksiazka_kocia':     'The Cat Gang! The cats are off on an adventure.',
    'ksiazka_pirat':     'Pirate Rhubarb! We are sailing for treasure.',
    'ksiazka_autka':     'Cars! Lightning McQueen is racing round the track.',
    'ksiazka_przytulas': 'The end of the book. Give Mum a goodnight hug!',
    'ksiazka_dobranoc':  'Lights out. Good night Franek!',
    'ksiazka_kto': 'Who is putting you to bed today? Left arrow is Mum, right arrow is Dad. '
                   'The other one gets a hug.',
    'ksiazka_czyta_mama': 'Mum will read to you.',
    'ksiazka_czyta_tata': 'Dad will read to you.',
    'ksiazka_przytulas_mama': 'The end of the book. Give Mum a goodnight hug!',
    'ksiazka_przytulas_tata': 'The end of the book. Give Dad a goodnight hug!',
    'sen_jak':    'Franek is asleep. And in his dream the cats are throwing snowballs! '
                  'The up arrow throws a snowball.',
    'sen_koniec': 'Sleep tight Franek. The cats throw snowballs all night long.',
})

NARRACJA_EN.update({
    # --- kapsułki, liczenie, gra w grze, tory, Baba Jaga, lawa, zwierzaki ---
    'zad_kapsulki':   'After breakfast it is capsule time. Eat four fish and strawberry capsules!',
    'kaps_2':         'Second capsule!',
    'kaps_3':         'Third capsule!',
    'kaps_4':         'The last one, the fourth capsule!',
    'kapsulki_mniam': 'Four capsules eaten! Fish and strawberry. Well done Franek!',
    'licz_poziom': 'Counting apples at preschool.',
    'licz_jak':    'There are three numbers under the apples. The left and right arrows show them, '
                   'the up arrow picks one. And the down arrow counts with you.',
    'licz_ile':    'How much is',
    'licz_plus':   'plus',
    'licz_razem':  'Let us count together!',
    'licz_brawo':  'Well done! Altogether it is',
    'licz_nie':    'That is not it. Let us count again.',
    'licz_koniec': 'All counted! You are a real mathematician, Franek!',
    'licz_1':  'one',
    'licz_2':  'two',
    'licz_3':  'three',
    'licz_4':  'four',
    'licz_5':  'five',
    'licz_6':  'six',
    'licz_7':  'seven',
    'licz_8':  'eight',
    'licz_9':  'nine',
    'licz_10': 'ten',
    'gierka_poziom': "Franek gets a tablet and plays Franek's Morning. A game inside the game!",
    'gierka_jak':    'A tiny Franek walks around in the little game. The left and right arrows '
                     'move him, the up arrow jumps. Collect three things.',
    'gierka_1':      'A tiny breakfast!',
    'gierka_2':      'A tiny toothbrush!',
    'gierka_3':      'Tiny shoes!',
    'gierka_koniec': 'Game over! Franek puts the tablet down. Off we go!',
    'rail_poziom': 'Franek is laying tracks for his train.',
    'rail_jak':    'The tracks are all turned the wrong way. The left and right arrows pick a '
                   'track, the up arrow turns it. Make the whole way from station to station!',
    'rail_pasuje': 'This track fits!',
    'rail_jedzie': 'The tracks are ready! Here comes the train! Choo, choo!',
    'rail_koniec': 'The train got to the station. Well done Franek!',
    'baba_poziom':  'At the playground we play red light, green light.',
    'baba_jak':     'While the witch has her back to you and sings, run! Press the left and right '
                    'arrows one after the other. When she turns around, freeze like a statue!',
    'baba_raz':     'One, two, three, red light!',
    'baba_stoj':    'Freeze! Do not move!',
    'baba_lapie':   'She saw you! You go back a little.',
    'baba_wygrana': 'You made it all the way! You win! Well done Franek!',
    'lawa_poziom': 'The floor is lava!',
    'lawa_jak':    'The whole floor is hot lava! Jump on the furniture with the up arrow and get '
                   'all the way to the sofa. Do not touch the floor!',
    'lawa_ups':    'Oops, lava! Back to the last piece of furniture.',
    'lawa_polowa': 'Halfway there! Keep jumping!',
    'lawa_koniec': 'You are on the sofa! The lava did not get you. Well done Franek!',
    'zwierzaki_poziom': 'The cats and the rabbit want their breakfast too.',
    'zad_karma_kot':    'Take the cat food!',
    'zad_kot1':         'Feed the first cat!',
    'zad_kot2':         'Now the second cat! He is up on the shelf.',
    'zad_marchewka':    'Take a carrot for the rabbit!',
    'zad_krolik':       'Feed the rabbit!',
    'zwierzaki_koniec': 'The cats are purring and the rabbit is crunching his carrot. '
                        'Everyone is fed! Well done Franek!',
    # --- pogoda, sznurówki, stół, porządki ---
    'pog_poziom':  'Look what the weather is like and dress for it.',
    'pog_jak':     'Look out of the window at the weather. The left and right arrows choose the '
                   'clothes, the up arrow puts them on.',
    'pog_deszcz':  'It is raining! What do we put on?',
    'pog_snieg':   'It is snowing and it is freezing! What do we put on?',
    'pog_slonce':  'The sun is shining and it is warm! What do we put on?',
    'pog_kalosze': 'Wellies and an umbrella.',
    'pog_czapka':  'A warm hat and a scarf.',
    'pog_okulary': 'A cap and sunglasses.',
    'pog_dobrze':  'Exactly right! You will be comfy in that. Well done!',
    'pog_zle':     'You would not be comfy in that. Have another look out of the window.',
    'pog_koniec':  'You know what to wear in any weather! Well done Franek!',
    'szn_poziom':   'We are learning to tie our shoes.',
    'szn_jak':      'Thread the lace through the holes. Press the left and right arrows one '
                    'after the other.',
    'szn_kokardka': 'All the holes are done! Now the bow. Press the up arrow and pull it tight.',
    'szn_koniec':   'You tied your shoes all by yourself! What a big boy. Well done Franek!',
    'stol_poziom':   'We are setting the table.',
    'stol_jak':      'Three people are sitting at the table. The left and right arrows pick a '
                     'seat, and the up arrow puts the thing down.',
    'stol_talerze':  'Plates first. Everyone gets one.',
    'stol_kubki':    'Now the cups. One for each person again.',
    'stol_widelce':  'And the forks. The last thing!',
    'stol_juz_jest': 'There is one there already. Choose another seat.',
    'stol_koniec':   'The table is set like in a restaurant! Dinner can begin. Well done!',
    'porz_poziom':     'After playing we have to tidy the room.',
    'porz_jak':        'The bricks go in the box and the teddies go on the shelf. Walk with the '
                       'left and right arrows, and pick things up with the up arrow.',
    'porz_klocek':     'You have a brick. Take it to the box!',
    'porz_mis':        'You have a teddy. Take it to the shelf!',
    'porz_zle_klocek': 'Bricks go in the box, not on the shelf.',
    'porz_zle_mis':    'Teddies sit on the shelf, not in the box.',
    'porz_koniec':     'Everything in its place! What a tidy room. Well done Franek!',
    'ksz_poziom':      'We are playing with colours and shapes.',
    'ksz_jak':         'The left and right arrows show the shapes, and the up arrow picks one.',
    'ksz_ktory_kolor': 'Which one is',
    'ksz_gdzie':       'Where is the',
    'ksz_czerwony':    'red',
    'ksz_niebieski':   'blue',
    'ksz_zielony':     'green',
    'ksz_zolty':       'yellow',
    'ksz_kolko':       'circle',
    'ksz_kwadrat':     'square',
    'ksz_trojkat':     'triangle',
    'ksz_brawo':       'Exactly! It is the',
    'ksz_nie':         'Not that one. Have another look.',
    'ksz_koniec':      'You got every colour and shape! Well done Franek!',
    'rytm_poziom':  'The teacher claps a rhythm and you copy it.',
    'rytm_jak':     'The teacher claps a rhythm with the arrows. Watch, listen and copy it '
                    'exactly the same.',
    'rytm_sluchaj': 'Listen and watch!',
    'rytm_powtorz': 'Now you! Copy the rhythm.',
    'rytm_dobrze':  'Perfect, the very same rhythm! Well done!',
    'rytm_zle':     'Oops, that is a different rhythm. Have another look.',
    'rytm_koniec':  'Every rhythm copied! You are a real musician!',
    'zupa_poziom':  'Lunch at preschool. Soup today.',
    'zupa_jak':     'The soup is too hot! Hold the up arrow and blow until it stops steaming.',
    'zupa_ostygla': 'It is fine now, it will not burn you! Eat it spoon by spoon. Press the '
                    'left and right arrows one after the other.',
    'zupa_koniec':  'An empty plate! All the soup is gone. Well done Franek!',
    'banki_poziom': 'There are soap bubbles in the bath.',
    'banki_jak':    'Catch the bubbles with your hand! The left and right arrows move your hand, '
                    'and a bubble pops the moment you touch it.',
    'banki_koniec': 'All the bubbles popped! What fun. Well done Franek!',
    'owce_poziom': 'Before we sleep we count sheep.',
    'owce_jak':    'A sheep walks up to the fence and waits. Press the up arrow to make it jump, '
                   'and I will count.',
    'owce_koniec': 'Ten sheep jumped over the fence. Franek is falling asleep. Good night!',
    'igloo_poziom':  'In his dream the cats are building an igloo out of snow.',
    'igloo_jak':     'The cat waves his paw when he is ready for a snowball. Press the up arrow '
                     'then and throw him one.',
    'igloo_czekaj':  'Wait until the cat waves his paw!',
    'igloo_rosnie':  'The igloo is growing! Keep throwing!',
    'igloo_koniec':  'The igloo is finished! The cats go inside to sleep. Good night Franek!',
    # --- menu i nowe gry edukacyjne ---
    'menu_jak':    "Franek's Morning! Press the left or right arrow to change the language, "
                   'the down arrow to change the mode, and the up arrow to start.',
    'menu_jezyk':  'English.',
    'menu_prosty': 'Simple mode. Shorter stages and nothing repeats.',
    'menu_pelny':  'Full mode. Every single stage and a whole long day.',
    'alf_poziom':  'Letters! Which letter does the word start with?',
    'alf_jak':     'Look at the picture and listen. Then the left and right arrows show the '
                   'letters, and the up arrow picks one.',
    'alf_pytanie': 'Which letter does it start with?',
    'alf_brawo':   'Yes! It starts with',
    'alf_nie':     'Not that letter. Say the word slowly and listen to the beginning.',
    'alf_koniec':  'You know your letters! Well done Franek!',
    'alf_kot':       'Cat.',
    'alf_rybka':     'Fish.',
    'alf_czapka':    'Hat.',
    'alf_mleko':     'Milk.',
    'alf_buty':      'Shoes.',
    'alf_lyzka':     'Spoon.',
    'alf_krolik':    'Rabbit.',
    'alf_marchewka': 'Carrot.',
    'mem_poziom': 'Pairs of pictures. Find two the same.',
    'mem_jak':    'The cards are face down. The left and right arrows move your hand, the up '
                  'arrow turns a card over. Find two the same.',
    'mem_para':   'A pair! Well done!',
    'mem_nie':    'Not a pair. Remember where they are and try again.',
    'mem_koniec': 'You found all the pairs! What a memory!',
    'wzor_poziom':   'Patterns! Work out what comes next.',
    'wzor_jak':      'The shapes go in a pattern that repeats. Work out what comes next. The left '
                     'and right arrows choose, the up arrow picks.',
    'wzor_co_dalej': 'What comes next?',
    'wzor_brawo':    'Yes! That is the pattern. Well done!',
    'wzor_nie':      'Not that one. Look at the pattern from the start.',
    'wzor_koniec':   'Every pattern worked out! You are a real detective!',
    'nie_poziom': 'Which one does not belong?',
    'nie_jak':    'Three pictures are from the same family and one is not. The left and right '
                  'arrows choose, the up arrow picks.',
    'nie_ktore':  'Which one does not belong?',
    'nie_brawo':  'Yes, that one does not belong!',
    'nie_nie':    'That one does belong. Have another look.',
    'nie_koniec': 'All sorted! You are a clever one!',
    'nie_zwierzeta': 'The others are all animals.',
    'nie_jedzenie':  'The others are all food.',
    'nie_ubrania':   'The others are all clothes.',
    'nie_zabawki':   'The others are all toys.',
    'nie_kuchnia':   'The others all belong in the kitchen.',
    'karty_poziom': 'Which card is higher?',
    'karty_jak':    'There are two cards. Pick the one with the bigger number. The left and right '
                    'arrows choose, the up arrow picks.',
    'karty_ktora':  'Which card is bigger?',
    'karty_brawo':  'Yes! The bigger number is',
    'karty_nie':    'No, the other one is bigger. Count the hearts.',
    'karty_koniec': 'You know your numbers! You always know which one is bigger!',
    'karty_as':     'The ace! The ace beats every number.',
    # --- minigra: zgadywanie literek ze słuchu ---
    'zgad_poziom':  'Guess the letters! Listen and find the one I say.',
    'zgad_jak':     'I will say a letter and you find it. The left and right arrows choose, '
                    'the up arrow picks it, and the down arrow says the letter again.',
    'zgad_szukamy': 'We are looking for the letter',
    'zgad_brawo':   'Yes, that is the letter! Well done!',
    'zgad_nie':     'Not that one. You picked the letter',
    'zgad_a_szukamy': 'And we are looking for the letter',
    'zgad_koniec':  'You know all your letters! Well done!',
    # --- minigra: układanie słów z liter ---
    'pisz_poziom': 'Let us write words! Build the word out of letters.',
    'pisz_jak':    'Look at the picture and build the word. The left and right arrows choose '
                   'a letter, the up arrow adds it, and the down arrow says the word again.',
    'pisz_slowo':  'Build the word:',
    'pisz_brawo':  'The whole word is done! Well done!',
    'pisz_nie':    'Not that letter. Listen to the word again.',
    'pisz_koniec': 'Every word written! You are a real writer!',
})
